### PR TITLE
Overflowing dayLimitUsed of PwayCompany contract

### PR DESCRIPTION
**Pull request by catageek**

### CODE REVIEW

**Comment by catageek** [comment]
Of course the overflow can be reproduced with Ethers also, but I give the proof with tokens only. Feel free to ask the ether version if really needed.

**Comment by adamskrodzki** [comment]
@catageek 
That is a valid bug and unexpected, but to perform this attack You need to have control over one of 3 administrators identities, so It qualifies to:

Major - 0.6 ETH all above with slight difference - is exists a workaround to a bug and do not require immediately code redeployment.

**Comment by lukaszGrynasz** [comment]
> this overflow allows to transfer tokens above daily limits without limitation by resetting dayLimitUsed to zero each time.
> 
> Of course the overflow can be reproduced with Ethers also, but I give the proof with tokens only. Feel free to ask the ether version if really needed.

@catageek is Your address ETH is 0x1825783589c5d58795F033d581F24828dd1E38FF ( gitcoin shows me it when i want to make a transfer ) or 0x00f9474f1f603de1c3ba6fbe525de1ffb389125b ( from Your fulfillmentId ) ?

**Comment by catageek** [comment]
> > this overflow allows to transfer tokens above daily limits without limitation by resetting dayLimitUsed to zero each time.
> > Of course the overflow can be reproduced with Ethers also, but I give the proof with tokens only. Feel free to ask the ether version if really needed.
> 
> @catageek is Your address ETH is 0x1825783589c5d58795F033d581F24828dd1E38FF ( gitcoin shows me it when i want to make a transfer ) or 0x00f9474f1f603de1c3ba6fbe525de1ffb389125b ( from Your fulfillmentId ) ?

It's 0x00f9474f1f603DE1c3BA6FbE525dE1FFb389125B.

**Pull request merged**
